### ISSUE TITLE
[Discussion] Move to "GPMDP"

### ISSUE THREAD

**Issue by MarshallOfSound** [GPMDP/google-play-music-desktop-remote#1]
Hey @mmazzarolo 

I was wondering what your thoughts were on moving this repository over to the [GPMDP Organization](https://github.com/GPMDP).

Obviously you would retain ownership/admin rights on the repository but I would like to make this almost the "official" remote for the "unofficial" player :laughing: .  I had a play around with the code for the last few hours and I really like the way it works so :+1: 

What do you think about moving it over?

**Comment by mmazzarolo** [comment]
Hey there!  :sun_with_face: 
  
Sure, seems nice!  
Honestly in the last month I've been busy but I recently planned to add some new stuff to it:  
- Finalize the zeroconf setup (the one you suggested was moved)  
- Add a screen for handling the network setup
- Handling state change with MobX
- Adding Unit Tests
- Make it more serious with errors handling/etc..

...But I was waiting for info on new endpoints first (honestly I stopped following the gmusic-utils status: do you have any news regarding possible endpoints?)

**Comment by MarshallOfSound** [comment]
Sweet, I can't remember exactly how to move a repository but Google should make that easy :+1: 

Seems like a solid **TODO** list :smile: 

RE new endpoints.  It's been a struggle but I'll be making a PR soon for `queue` endpoints.  (Getting the queue, removing things from the queue and playing things in the queue).  Other endpoints are really hard to do so probably won't happen :cry:

**Comment by mmazzarolo** [comment]
Cool, the queue endpoint was on the top of my list!

I'm on mobile right now, but I'll try to transfer it as soon as I can :+1:

**Comment by mmazzarolo** [comment]
Done! :surfer:
