### ISSUE TITLE
[Android] Allow media keys to control playback

### ISSUE THREAD

**Issue by Kisty** [GPMDP/google-play-music-desktop-remote#18]
Would be great to enable media keys for playback. I know how to do this in vanilla Android. Is it possible to do so using the Android SDK in the app?

**Comment by Kisty** [comment]
Oh, apparently it's already implemented, but it doesn't work with swiping two fingers down on my OnePlus. Might I suggest using Android's [MediaSession](https://developer.android.com/guide/topics/media-apps/working-with-a-media-session.html) API?

**Comment by MarshallOfSound** [comment]
We do already use `MediaSessionCompat` internally

https://github.com/GPMDP/google-play-music-desktop-remote/blob/master/android/app/src/main/java/com/marshallofsound/gpmdp/remote/InternalMediaService.java#L58

**Comment by Kisty** [comment]
Thanks for getting back. Then why doesn't the two fingers swipe down work to pause/play, then? I'll try and do the same with my bluetooth headphones to see if the issue happens with them

**Comment by Kisty** [comment]
Hmm, so my bluetooth headphones too are not causing the playback to pause or play. Can you double check this works on your end?

**Comment by MarshallOfSound** [comment]
This definitely works on my end, I use this every day 😄 Idk what command your headphones are sending out but it isn't going into media sessions 🤔

**Comment by Kisty** [comment]
Very strange. Thanks for this app and desktop app. Very helpful!

**Comment by Kisty** [comment]
Still doesn't work. Going to try and build the app and run on an emulator to see if I can repro with that.
