### ISSUE TITLE
Bug with song switching

### ISSUE THREAD

**Issue by KakoitoTatar** [GPMDP/google-play-music-desktop-remote#19]
When Show track information in Windows 10 volume overlay is enabled, pressing on next or previous player button is skiped two song at one press
![image](https://user-images.githubusercontent.com/24491062/36587880-f6a0cd26-18b8-11e8-99ec-94ece45c9728.png)

**Comment by jostrander** [comment]
Wrong repository. See https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues

Please search before opening this issue over there because one already exists.
