### ISSUE TITLE
No album art or playlist information 

### ISSUE THREAD

**Issue by maxideus** [GPMDP/google-play-music-desktop-remote#4]
Downloaded the latest Android build on a BlackBerry Priv running Marshmallow 6.0.1 and was able to control the playlist (pause, forward, backwards, etc), although, no information or artwork was available about the song being played.

**Comment by MarshallOfSound** [comment]
This is not a bug rather an unimplemented feature.  The app is barely in beta so instead of raising issues can you just start a discussion in [gitter](https://gitter.im/GPMDP/google-play-music-desktop-remote). 

Cheers

**Comment by maxideus** [comment]
Ah sorry, I'm a newbie to Github, so I was unsure where to inquire about the feature.  I'll use the Gitter chat as mentioned.

**Comment by MarshallOfSound** [comment]
@maxideus All good, normally you would raise an issue like you did.  But in this particular case this app is barely beta and as such I would prefer stuff doesn't clog up the issues :+1:
