### ISSUE TITLE
How to connect a tablet?

### ISSUE THREAD

**Issue by sebastienserre** [GPMDP/google-play-music-desktop-remote#8]
Hello,

I've an ANdroid Tablet with the app installed.
I've activated on my desktop GPMDP settings the Payback PAI
but the remote app doesn't find the Desktop in the Device list

Tablet is a Samsung Galaxy Note 10.1

**Comment by MarshallOfSound** [comment]
Please keep support requests out of the GitHub issues section.  It is intended to be for bugs / feature requests only.

> but the remote app doesn't find the Desktop in the Device list

Quite possibly you have a firewall blocking either the app, the client or the bonjour service in the middle.  Try typing in your IP address manually.
